[keyboard]

bindings = [
  { key = "C", mods = "Control", action = "Copy" },
  { key = "V", mods = "Control", action = "Paste" },
  { key = "PageUp", mods = "Control", action = "ScrollLineUp" },
  { key = "PageDown", mods = "Control", action = "ScrollLineDown" },
  { key = "PageUp", action = "ScrollPageUp" },
  { key = "PageDown", action = "ScrollPageDown" },
  { key = "Home", action = "ScrollToTop" },
  { key = "End", action = "ScrollToBottom" },
  { key = "Backspace", mods = "Control", action = "ResetFontSize" },
]